fetch('https://api.jikan.moe/v4/seasons/now?sfw')
.then((res) => res.json())
.then((data) => {
  const carouselData = data.data;
  // SLIDE 1
  document.getElementById('img-slide-1').src = `${carouselData[0].images.webp.large_image_url}`;
  document.getElementById('img-slide-1-s').src = `${carouselData[0].images.webp.large_image_url}`;
  document.getElementById('title-slide-1').textContent = `${carouselData[0].title}`;
  document.getElementById('type-slide-1').textContent = `${carouselData[0].type}`;
  document.getElementById('duration-slide-1').textContent = `${carouselData[0].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-1').textContent = `${carouselData[0].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-1').textContent = `${carouselData[0].synopsis}`;
  // SLIDE 2
  document.getElementById('img-slide-2').src = `${carouselData[1].images.webp.large_image_url}`;
  document.getElementById('img-slide-2-s').src = `${carouselData[1].images.webp.large_image_url}`;
  document.getElementById('title-slide-2').textContent = `${carouselData[1].title}`;
  document.getElementById('type-slide-2').textContent = `${carouselData[1].type}`;
  document.getElementById('duration-slide-2').textContent = `${carouselData[1].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-2').textContent = `${carouselData[1].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-2').textContent = `${carouselData[1].synopsis}`;
  // SLIDE 3
  document.getElementById('img-slide-3').src = `${carouselData[2].images.webp.large_image_url}`;
  document.getElementById('img-slide-3-s').src = `${carouselData[2].images.webp.large_image_url}`;
  document.getElementById('title-slide-3').textContent = `${carouselData[2].title}`;
  document.getElementById('type-slide-3').textContent = `${carouselData[2].type}`;
  document.getElementById('duration-slide-3').textContent = `${carouselData[2].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-3').textContent = `${carouselData[2].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-3').textContent = `${carouselData[2].synopsis}`;
  // SLIDE 4
  document.getElementById('img-slide-4').src = `${carouselData[3].images.webp.large_image_url}`;
  document.getElementById('img-slide-4-s').src = `${carouselData[3].images.webp.large_image_url}`;
  document.getElementById('title-slide-4').textContent = `${carouselData[3].title}`;
  document.getElementById('type-slide-4').textContent = `${carouselData[3].type}`;
  document.getElementById('duration-slide-4').textContent = `${carouselData[3].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-4').textContent = `${carouselData[3].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-4').textContent = `${carouselData[3].synopsis}`;
  // SLIDE 5
  document.getElementById('img-slide-5').src = `${carouselData[4].images.webp.large_image_url}`;
  document.getElementById('img-slide-5-s').src = `${carouselData[4].images.webp.large_image_url}`;
  document.getElementById('title-slide-5').textContent = `${carouselData[4].title}`;
  document.getElementById('type-slide-5').textContent = `${carouselData[4].type}`;
  document.getElementById('duration-slide-5').textContent = `${carouselData[4].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-5').textContent = `${carouselData[4].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-5').textContent = `${carouselData[4].synopsis}`;
  // SLIDE 6
  document.getElementById('img-slide-6').src = `${carouselData[5].images.webp.large_image_url}`;
  document.getElementById('img-slide-6-s').src = `${carouselData[5].images.webp.large_image_url}`;
  document.getElementById('title-slide-6').textContent = `${carouselData[5].title}`;
  document.getElementById('type-slide-6').textContent = `${carouselData[5].type}`;
  document.getElementById('duration-slide-6').textContent = `${carouselData[5].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-6').textContent = `${carouselData[5].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-6').textContent = `${carouselData[5].synopsis}`;
  // SLIDE 7
  document.getElementById('img-slide-7').src = `${carouselData[6].images.webp.large_image_url}`;
  document.getElementById('img-slide-7-s').src = `${carouselData[6].images.webp.large_image_url}`;
  document.getElementById('title-slide-7').textContent = `${carouselData[6].title}`;
  document.getElementById('type-slide-7').textContent = `${carouselData[6].type}`;
  document.getElementById('duration-slide-7').textContent = `${carouselData[6].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-7').textContent = `${carouselData[6].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-7').textContent = `${carouselData[6].synopsis}`;
  // SLIDE 8
  document.getElementById('img-slide-8').src = `${carouselData[7].images.webp.large_image_url}`;
  document.getElementById('img-slide-8-s').src = `${carouselData[7].images.webp.large_image_url}`;
  document.getElementById('title-slide-8').textContent = `${carouselData[7].title}`;
  document.getElementById('type-slide-8').textContent = `${carouselData[7].type}`;
  document.getElementById('duration-slide-8').textContent = `${carouselData[7].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-8').textContent = `${carouselData[7].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-8').textContent = `${carouselData[7].synopsis}`;
  // SLIDE 9
  document.getElementById('img-slide-9').src = `${carouselData[8].images.webp.large_image_url}`;
  document.getElementById('img-slide-9-s').src = `${carouselData[8].images.webp.large_image_url}`;
  document.getElementById('title-slide-9').textContent = `${carouselData[8].title}`;
  document.getElementById('type-slide-9').textContent = `${carouselData[8].type}`;
  document.getElementById('duration-slide-9').textContent = `${carouselData[8].duration.split("per")[0]}`;
  document.getElementById('aired-date-slide-9').textContent = `${carouselData[8].aired.string.split("to")[0]}`;
  document.getElementById('synopsis-slide-9').textContent = `${carouselData[8].synopsis}`;
  }
);